---
## Append samples of your project ##
resources:
  - netbox_v1_ipaddress.yaml
  - netbox_v1_ipaddressclaim.yaml
  - netbox_v1_prefix.yaml
  - netbox_v1_prefixclaim.yaml
  - netbox_v1_prefixclaim_parentprefixselector_bool_int.yaml
  - netbox_v1_prefixclaim_parentprefixselector.yaml
  - netbox_v1_iprangeclaim.yaml
  - netbox_v1_iprange.yaml
  - netbox_v1_ipaddress_vrf.yaml
  - netbox_v1_ipaddressclaim_vrf.yaml
  - netbox_v1_prefix_vrf.yaml
  - netbox_v1_prefixclaim_vrf.yaml
  - netbox_v1_iprange_vrf.yaml
  - netbox_v1_iprangeclaim_vrf.yaml
  # +kubebuilder:scaffold:manifestskustomizesamples
