---
## Append samples of your project ##
resources:
  - netbox_v1_ipaddress.yaml
  - netbox_v1_ipaddressclaim.yaml
  - netbox_v1_prefix.yaml
  - netbox_v1_prefixclaim.yaml
  - netbox_v1_prefixclaim_parentprefixselector_bool_int.yaml
  - netbox_v1_prefixclaim_parentprefixselector.yaml
  - netbox_v1_iprangeclaim.yaml
  - netbox_v1_iprange.yaml
  #+kubebuilder:scaffold:manifestskustomizesamples
