## Append samples of your project ##
resources:
- netbox_v1_ipaddress.yaml
- netbox_v1_ipaddressclaim.yaml
- netbox_v1_prefix.yaml
- netbox_v1_prefixclaim.yaml
- netbox_v1_prefixclaim_customfields.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
