apiVersion: netbox.dev/v1
kind: VLANClaim
metadata:
  name: vlanclaim-dynamic-sample
spec:
  # vlanId is omitted - the operator will allocate the next available VID
  site: Site-1
  vlanGroup: Group-1
  description: "Dynamic VLAN Claim - VID allocated automatically"
  preserveInNetbox: false
