---
apiVersion: netbox.dev/v1
kind: IpAddress
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: ipaddress-vrf-sample
spec:
  tenant: "MY_TENANT"
  vrf: "MY_VRF"
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  ipAddress: "4.0.0.100/32"
