---
apiVersion: netbox.dev/v1
kind: IpRangeClaim
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: iprangeclaim-vrf-sample
spec:
  tenant: "MY_TENANT"
  vrf: "MY_VRF"
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  parentPrefix: "4.1.0.0/24"
  size: 3
