---
apiVersion: netbox.dev/v1
kind: Prefix
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: prefix-sample
spec:
  tenant: "Dunder-Mifflin, Inc."
  site: "DM-Akron"
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  prefix: "2.0.0.0/24"
  tags:
    - name: Alpha
    - slug: golf
    - name: Bravo
