---
apiVersion: netbox.dev/v1
kind: IpRange
metadata:
  labels:
    app.kubernetes.io/name: netbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: iprange-vrf-sample
spec:
  tenant: "MY_TENANT"
  vrf: "MY_VRF"
  description: "some description"
  comments: "your comments"
  preserveInNetbox: true
  startAddress: "4.1.0.200/32"
  endAddress: "4.1.0.202/32"
